In [2]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura_em_metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [9]:
lista_de_centimetros = list(range(170, 190, 5))
lista_de_centimetros

print("Lista de alturas em centímetros:", lista_de_centimetros)

Lista de alturas em centímetros: [170, 175, 180, 185]


In [10]:
altura_em_centimetros = np.array(lista_de_centimetros)

print("Array de alturas em centímetros:", altura_em_centimetros)

Array de alturas em centímetros: [170 175 180 185]


In [11]:
altura_em_metros = altura_em_centimetros / 100

print("Array de alturas em metros:", altura_em_metros)

Array de alturas em metros: [1.7  1.75 1.8  1.85]


### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [15]:
lista_pesos = [70, 75, 80, 85]
lista_pesos
# seu código aqui
print("Lista de pesos em Kg:", lista_pesos)

Lista de pesos em Kg: [70, 75, 80, 85]


In [16]:
pesos = np.array(lista_pesos)

print("Array de pesos em Kg:", pesos)

Array de pesos em Kg: [70 75 80 85]


In [18]:
# calcule o IMC dessas pessoas

imc = pesos / (altura_em_metros ** 2)

imc = np.round(imc, 2)

print("Array de IMC:", imc)

Array de IMC: [24.22 24.49 24.69 24.84]


### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [19]:
# lista dados_financeiros
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
dados_financeiros
#i) transforme essa lista em um ndarray

nd_financeiros = np.array(dados_financeiros)

print("nd_financeiros:\n", nd_financeiros)

nd_financeiros:
 [[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]


In [20]:
# ii)

nd_financeiros = nd_financeiros.transpose()
print("nd_financeiros transposto:\n", nd_financeiros)

print("Segunda linha:", nd_financeiros[1])

print("Segunda coluna:", nd_financeiros[:, 1])


nd_financeiros transposto:
 [[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000  7000]
 [10000  5000 16000]]
Segunda linha: [2500 2500 5500]
Segunda coluna: [1000 2500 3000 5000]


In [21]:
# iii) Calcule o endividamento total

endividamento_total = nd_financeiros[:, 0] + nd_financeiros[:, 1]

print("Endividamento total:\n", endividamento_total)

Endividamento total:
 [ 4000  5000  4000 15000]


In [27]:
# iv) corrigindo um valor específico

nd_financeiros[2, 2] = 10000

print("nd_financeiros:\n", nd_financeiros)

nd_financeiros:
 [[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000 10000]
 [10000  5000 16000]]


In [26]:
endividamento_total_corrigido = nd_financeiros[:, 0] + nd_financeiros[:, 1]

print("Endividamento total corrigido:\n", endividamento_total_corrigido)

Endividamento total corrigido:
 [ 4000  5000  4000 15000]


### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os.

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [29]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [30]:
# i) crie o objeto bool_zero através do operador ==

bool_zero = (poi == 0)

print("bool_zero:\n", bool_zero)

bool_zero:
 [False False False False False False False False False  True False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False  True False False False False False False False False False False
 False False False False]


In [31]:
# ii) Conte a quantidade de zeros (ou some os elementos de bool_zero)

num_zeros = np.sum(bool_zero)

print("Número de valores zero:", num_zeros)

Número de valores zero: 6


In [35]:
# iii) utilize a indexação booleana para criar uma seleção de não-zeros
# dica: inverta o objeto bool_zero

poi_nao_zero = poi[~bool_zero]

print("Valores de poi diferentes de zero:\n", poi_nao_zero)

Valores de poi diferentes de zero:
 [3 3 6 2 4 5 4 4 2 3 3 2 8 2 3 3 3 4 4 2 6 6 3 4 3 5 2 1 3 2 2 3 2 4 4 5 7
 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4 1 1 7 1
 2 1 3 7 4 4 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
